[workspace]
members = [
    "rsa-generator",
    "github",
    "slack", "slack/wasm",
    "sendgrid", "sendgrid/wasm",
    "twitter",
    "gmail",
    "gitlab",
    "discord",
    "cloudinary",
    "twilio",
    "notion",
    "dropbox",
    "monday",
    "jira",
    "telegram",
    "genereq",
]
